"""
Market Data

Fetches real-time and historical market data for Brazilian listed companies
from Yahoo Finance (yfinance, free, no API key).

B3 tickers use the .SA suffix (e.g. PETR4.SA).

Synchronous — call fetch_market_data via asyncio.to_thread() from async code.
"""

import re
import unicodedata

import pandas as pd
import yfinance as yf


# ---------------------------------------------------------------------------
# Ticker map — normalized company name → B3 ticker
# ---------------------------------------------------------------------------

TICKER_MAP: dict[str, str] = {
    # Major aliases and common names
    "b3": "B3SA3.SA",
    "petrobras": "PETR4.SA",
    "petroleo brasileiro": "PETR4.SA",
    "petrobras pn": "PETR4.SA",
    "petrobras on": "PETR3.SA",
    "itau unibanco": "ITUB4.SA",
    "itau": "ITUB4.SA",
    "itausa": "ITSA4.SA",
    "cosan": "CSAN3.SA",
    "raizen": "RAIZ4.SA",
    "natura": "NATU3.SA",
    "natura co": "NATU3.SA",
    "magazine luiza": "MGLU3.SA",
    "magalu": "MGLU3.SA",
    "ambev": "ABEV3.SA",
    "copel": "CPLE3.SA",
    "cogna": "COGN3.SA",
    "bradesco": "BBDC4.SA",
    "banco bradesco": "BBDC4.SA",
    "banco bradeco": "BBDC4.SA",
    "cemig": "CMIG4.SA",
    "banco do brasil": "BBAS3.SA",
    "gerdau": "GGBR4.SA",
    "banrisul": "BRSR6.SA",
    "equatorial": "EQTL3.SA",
    "equatorial energia": "EQTL3.SA",
    "csn": "CSNA3.SA",
    "companhia siderurgica nacional": "CSNA3.SA",
    "siderurgica nacional": "CSNA3.SA",
    "lojas renner": "LREN3.SA",
    "renner": "LREN3.SA",
    "rumo": "RAIL3.SA",
    "btg pactual": "BPAC11.SA",
    "btg": "BPAC11.SA",
    "banco btg pactual": "BPAC11.SA",
    "grupo vamos": "VAMO3.SA",
    "vamos": "VAMO3.SA",
    "sabesp": "SBSP3.SA",
    "usiminas": "USIM5.SA",
    "assai": "ASAI3.SA",
    "oncoclinicas": "ONCO3.SA",
    "vale": "VALE3.SA",
    "eztec": "EZTC3.SA",
    "raia drogasil": "RADL3.SA",
    "raiadrogasil": "RADL3.SA",
    "rede dor": "RDOR3.SA",
    "rede d or": "RDOR3.SA",
    "localiza": "RENT3.SA",
    "marfrig": "MBRF3.SA",
    "caixa seguridade": "CXSE3.SA",
    "csn mineracao": "CMIN3.SA",
    "totvs": "TOTS3.SA",
    "axia energia": "AXIA3.SA",
    "anima": "ANIM3.SA",
    "anima educacao": "ANIM3.SA",
    "mrv": "MRVE3.SA",
    "motiva": "MOTV3.SA",
    "ccr": "MOTV3.SA",
    "metalurgica gerdau": "GOAU4.SA",
    "eneva": "ENEV3.SA",
    "weg": "WEGE3.SA",
    "movida": "MOVI3.SA",
    "allos": "ALOS3.SA",
    "vivo": "VIVT3.SA",
    "telefonica brasil": "VIVT3.SA",
    "minerva": "BEEF3.SA",
    "vibra": "VBBR3.SA",
    "vibra energia": "VBBR3.SA",
    "cvc": "CVCB3.SA",
    "cury": "CURY3.SA",
    "direcional": "DIRR3.SA",
    "jhsf": "JHSF3.SA",
    "prio": "PRIO3.SA",
    "petro rio": "PRIO3.SA",
    "petrorio": "PRIO3.SA",
    "c e a": "CEAB3.SA",
    "cea": "CEAB3.SA",
    "3r petroleum": "BRAV3.SA",
    "bb seguridade": "BBSE3.SA",
    "grupo mateus": "GMAT3.SA",
    "braskem": "BRKM5.SA",
    "ultrapar": "UGPA3.SA",
    "alpargatas": "ALPA4.SA",
    "odontoprev": "SAUD3.SA",
    "multiplan": "MULT3.SA",
    "marcopolo": "POMO4.SA",
    "cyrela": "CYRE3.SA",
    "ecorodovias": "ECOR3.SA",
    "isa energia": "ISAE4.SA",
    "construtora tenda": "TEND3.SA",
    "tenda": "TEND3.SA",
    "klabin": "KLBN11.SA",
    "dimed": "PNVL3.SA",
    "embraer": "EMBJ3.SA",
    "sanepar": "SAPR11.SA",
    "locaweb": "LWSA3.SA",
    "lwsa": "LWSA3.SA",
    "suzano": "SUZB3.SA",
    "hapvida": "HAPV3.SA",
    "grupo pao de acucar": "PCAR3.SA",
    "pao de acucar": "PCAR3.SA",
    "recrusul": "RCSL4.SA",
    "arezzo": "AZZA3.SA",
    "arezzo co": "AZZA3.SA",
    "yduqs": "YDUQ3.SA",
    "slc agricola": "SLCE3.SA",
    "engie": "EGIE3.SA",
    "engie brasil": "EGIE3.SA",
    "smart fit": "SMFT3.SA",
    "hidrovias do brasil": "HBSA3.SA",
    "vulcabras": "VULC3.SA",
    "tim": "TIMS3.SA",
    "tim brasil": "TIMS3.SA",
    "uniao pet": "AUAU3.SA",
    "pague menos": "PGMN3.SA",
    "copasa": "CSMG3.SA",
    "fleury": "FLRY3.SA",
    "intelbras": "INTB3.SA",
    "auren": "AURE3.SA",
    "auren energia": "AURE3.SA",
    "plano e plano": "PLPL3.SA",
    "cba": "CBAV3.SA",
    "gps": "GGPS3.SA",
    "lojas quero quero": "LJQQ3.SA",
    "paranapanema": "PMAM3.SA",
    "iguatemi": "IGTI11.SA",
    "jereissati participacoes": "IGTI11.SA",
    "hypera": "HYPE3.SA",
    "meliuz": "CASH3.SA",
    "simpar": "SIMH3.SA",
    "light": "LIGT3.SA",
    "camil": "CAML3.SA",
    "camil alimentos": "CAML3.SA",
    "sequoia logistica": "SEQL3.SA",
    "grupo sbf": "SBFG3.SA",
    "vivara": "VIVA3.SA",
    "petroreconcavo": "RECV3.SA",
    "petrorecsa": "RECV3.SA",
    "petro reconcavo": "RECV3.SA",
    "dexco": "DXCO3.SA",
    "randon": "RAPT4.SA",
    "banco abc brasil": "ABCB4.SA",
    "abc brasil": "ABCB4.SA",
    "cpfl": "CPFE3.SA",
    "cpfl energia": "CPFE3.SA",
    "grupo casas bahia": "BHIA3.SA",
    "casas bahia": "BHIA3.SA",
    "banco santander": "SANB11.SA",
    "santander brasil": "SANB11.SA",
    "santander": "SANB11.SA",
    "even": "EVEN3.SA",
    "enjoei": "ENJU3.SA",
    "espacolaser": "ESPA3.SA",
    "qualicorp": "QUAL3.SA",
    "log cp": "LOGG3.SA",
    "americanas": "AMER3.SA",
    "track field": "TFCO4.SA",
    "grendene": "GRND3.SA",
    "bradespar": "BRAP4.SA",
    "guararapes": "RIAA3.SA",
    "energisa": "ENGI11.SA",
    "iochpe maxion": "MYPK3.SA",
    "jalles machado": "JALL3.SA",
    "ferbasa": "FESA4.SA",
    "alupar": "ALUP11.SA",
    "boa safra": "SOJA3.SA",
    "boa safra sementes": "SOJA3.SA",
    "helbor": "HBOR3.SA",
    "m dias branco": "MDIA3.SA",
    "kepler weber": "KEPL3.SA",
    "positivo": "POSI3.SA",
    "mouradubeux": "MDNE3.SA",
    "moura dubeux": "MDNE3.SA",
    "3tentos": "TTEN3.SA",
    "tres tentos": "TTEN3.SA",
    "taesa": "TAEE11.SA",
    "sao martinho": "SMTO3.SA",
    "dasa": "DASA3.SA",
    "porto seguro": "PSSA3.SA",
    "porto": "PSSA3.SA",
    "jsl": "JSLG3.SA",
    "multilaser": "MLAS3.SA",
    "azevedo travassos": "AZEV4.SA",
    "azt energia": "AZTE3.SA",
    "unifique": "FIQE3.SA",
    "mills": "MILS3.SA",
    "banco bmg": "BMGB4.SA",
    "unipar": "UNIP6.SA",
    "ambipar": "AMBP3.SA",
    "tupy": "TUPY3.SA",
    "armac": "ARML3.SA",
    "wiz solucoes": "WIZC3.SA",
    "banco pine": "PINE4.SA",
    "priner": "PRNR3.SA",
    "viveo": "VVEO3.SA",
    "orizon": "ORVR3.SA",
    "lavvi": "LAVV3.SA",
    "lavvi incorporadora": "LAVV3.SA",
    "vitrubrepcm": "VTRU3.SA",
    "compass": "PASS3.SA",
    "gafisa": "GFSA3.SA",
    "irani": "RANI3.SA",
    "ser educacional": "SEER3.SA",
    "mitre": "MTRE3.SA",
    "mitre realty": "MTRE3.SA",
    "bemobi": "BMOB3.SA",
    "brisanet": "BRST3.SA",
    "valid": "VLID3.SA",
    "cruzeiro do sul educacional": "CSED3.SA",
    "schulz": "SHUL4.SA",
    "vittia": "VITT3.SA",
    "irb": "IRBR3.SA",
    "irb brasil": "IRBR3.SA",
    "desktop": "DESK3.SA",
    "oi": "OIBR3.SA",
    "blau": "BLAU3.SA",
    "blau farmaceutica": "BLAU3.SA",
    "oceanpact": "OPCT3.SA",
    "melnick": "MELK3.SA",
    "taurus": "TASA4.SA",
    "hbr realty": "HBRE3.SA",
    "eternit": "ETER3.SA",
    "allianca": "AALR3.SA",
    "alliança": "AALR3.SA",
    "trisul": "TRIS3.SA",
    "estapar": "ALPK3.SA",
    "br partners": "BRBI11.SA",
    "syn": "SYNE3.SA",
    "orangebtc": "OBTC3.SA",
    "industrias romi": "ROMI3.SA",
    "romi": "ROMI3.SA",
    "fras le": "FRAS3.SA",
    "fras-le": "FRAS3.SA",
    "tegma": "TGMA3.SA",
    "allied": "ALLD3.SA",
    "joao fortes": "JFEN3.SA",
    "toky": "TOKY3.SA",
    "mater dei": "MATD3.SA",
    "biomm": "BIOM3.SA",
    "mahle metal leve": "LEVE3.SA",
    "metal leve": "LEVE3.SA",
    "portobello": "PTBL3.SA",
    "viver": "VIVR3.SA",
    "neogrid": "NGRD3.SA",
    "profarma": "PFRM3.SA",
    "imc alimentacao": "MEAL3.SA",
    "brasilagro": "AGRO3.SA",
    "brasil agro": "AGRO3.SA",
    "lojas marisa": "AMAR3.SA",
    "marisa": "AMAR3.SA",
    "infracommerce": "IFCM3.SA",
    "dotz": "DOTZ3.SA",
    "lopes": "LPSB3.SA",
    "eucatex": "EUCA4.SA",
    "padtec": "PDTC3.SA",
    "dexxos": "DEXP3.SA",
    "d1000": "DMVF3.SA",
    "d1000 varejo farma": "DMVF3.SA",
    "csu cardsystem": "CSUD3.SA",
    "azul": "AZUL3.SA",
    "lupatech": "LUPA3.SA",
    "triunfo": "TPIS3.SA",
    "aeris energy": "AERI3.SA",
    "westwing": "WEST3.SA",
    "haga": "HAGA4.SA",
    "banco da amazonia": "BAZA3.SA",
    "banco mercantil do brasil": "BMEB4.SA",
    "tecnisa": "TCSA3.SA",
    "banco de brasilia": "BSLI3.SA",
    "renova energia": "RNEW4.SA",
    "log in": "LOGN3.SA",
    "log-in": "LOGN3.SA",
    "inepar": "INEP3.SA",
    "time for fun": "SHOW3.SA",
    "coelce": "COCE5.SA",
    "unicasa": "UCAS3.SA",
    "automob": "AMOB3.SA",
    "terra santa": "LAND3.SA",
    "alphaville": "AVLL3.SA",
    "minupar": "MNPR3.SA",
    "agrogalaxy": "AGXY3.SA",
    "sao carlos": "SCAR3.SA",
    "wdc networks": "WDCN3.SA",
    "technos": "TECN3.SA",
    "pdg realty": "PDGR3.SA",
    "mangels": "MGEL4.SA",
    "atom educacao e editora": "ATED3.SA",
    "hoteis othon": "HOOT4.SA",
    "ceb": "CEBR5.SA",
    "traders club": "TRAD3.SA",
    "equatorial energia para": "EQPA3.SA",
    "le lis blanc": "VSTE3.SA",
    "ourofino saude animal": "OFSA3.SA",
    "dohler": "DOHL4.SA",
    "cedro textil": "CEDO4.SA",
    "porto vm": "PSVM11.SA",
    "embpar participacoes": "EPAR3.SA",
    "electro aco altona": "EALT3.SA",
    "cambuci": "CAMB3.SA",
    "banestes": "BEES3.SA",
    "whirlpool": "WHRL4.SA",
    "nutriplant": "NUTR3.SA",
    "grazziotin": "CGRA4.SA",
    "energisa mt": "ENMT3.SA",
    "fictor alimentos": "FICT3.SA",
    "celesc": "CLSC4.SA",
    "fertilizantes heringer": "FHER3.SA",
    "trevisa": "LUXM4.SA",
    "arandu": "ARND3.SA",
    "wlm": "WLMM4.SA",
    "bioma": "BIED3.SA",
    "comgas": "CGAS5.SA",
    "refinaria de manguinhos": "RPMG3.SA",
    "rede energia": "REDE3.SA",
    "telebras": "TELB4.SA",
    "elektro": "EKTR4.SA",
    "banese": "BGIP4.SA",
    "revee": "RVEE3.SA",
    "metisa": "MTSA4.SA",
    "participacoes alianca da bahia": "PEAB3.SA",
    "coelba": "CEEB3.SA",
    "osx brasil": "OSXB3.SA",
    "emae": "EMAE4.SA",
    "bardella": "BDLL4.SA",
    "metalurgica riosulense": "RSUL4.SA",
    "sao paulo turismo": "AHEB3.SA",
    "josapar": "JOPA4.SA",
    "alfa holdings": "RPAD5.SA",
    "bombril": "BOBR4.SA",
    "monark": "BMKS3.SA",
    "panatlantica": "PATI3.SA",
    "tronox pigmentos": "CRPG5.SA",
    "ampla energia": "CBEE3.SA",
    "mundial": "MNDL3.SA",
    "equatorial maranhao": "EQMA3B.SA",
    "karsten": "CTKA4.SA",
    "baumer": "BALM4.SA",
    "estrela": "ESTR4.SA",
    "contax": "CTAX3.SA",
    "rio paranapanema energia": "GEPA4.SA",
    "banco mercantil de investimentos": "BMIN4.SA",
    "ppla": "PPLA11.SA",
    "nordon": "NORD3.SA",
    "brasil brokers": "NEXP3.SA",
    "melhoramentos": "MSPA3.SA",
    "plascar": "PLAS3.SA",
    "dtcom": "DTCY3.SA",
    "habitasul": "HBTS5.SA",
    "sondotecnica": "SOND6.SA",
    "mrs logistica": "MRSA3B.SA",
    "banco do nordeste": "BNBR3.SA",
    "sansuy": "SNSY3.SA",
    "excelsior": "BAUH4.SA",
    "adolpho lindenberg": "CALI3.SA",
    "afluente t": "AFLT3.SA",
    "naturgy ceg": "CEGR3.SA",
    "metalfrio": "FRIO3.SA",
    "cemepe": "MAPT4.SA",
    "fica": "FIEI3.SA",
    "wetzel": "MWET4.SA",

    # Direct ticker keys, useful when the extractor returns ticker-like text
    "b3sa3": "B3SA3.SA",
    "petr4": "PETR4.SA",
    "itub4": "ITUB4.SA",
    "itsa4": "ITSA4.SA",
    "csan3": "CSAN3.SA",
    "raiz4": "RAIZ4.SA",
    "natu3": "NATU3.SA",
    "mglu3": "MGLU3.SA",
    "abev3": "ABEV3.SA",
    "cple3": "CPLE3.SA",
    "cogn3": "COGN3.SA",
    "bbdc4": "BBDC4.SA",
    "cmig4": "CMIG4.SA",
    "bbas3": "BBAS3.SA",
    "ggbr4": "GGBR4.SA",
    "brsr6": "BRSR6.SA",
    "eqtl3": "EQTL3.SA",
    "csna3": "CSNA3.SA",
    "lren3": "LREN3.SA",
    "rail3": "RAIL3.SA",
    "bpac11": "BPAC11.SA",
    "vamo3": "VAMO3.SA",
    "sbsp3": "SBSP3.SA",
    "usim5": "USIM5.SA",
    "asai3": "ASAI3.SA",
    "petr3": "PETR3.SA",
    "onco3": "ONCO3.SA",
    "vale3": "VALE3.SA",
    "eztc3": "EZTC3.SA",
    "radl3": "RADL3.SA",
    "rdor3": "RDOR3.SA",
    "rent3": "RENT3.SA",
    "mbrf3": "MBRF3.SA",
    "cxse3": "CXSE3.SA",
    "cmin3": "CMIN3.SA",
    "tots3": "TOTS3.SA",
    "axia3": "AXIA3.SA",
    "anim3": "ANIM3.SA",
    "mrve3": "MRVE3.SA",
    "motv3": "MOTV3.SA",
    "goau4": "GOAU4.SA",
    "enev3": "ENEV3.SA",
    "wege3": "WEGE3.SA",
    "movi3": "MOVI3.SA",
    "alos3": "ALOS3.SA",
    "vivt3": "VIVT3.SA",
    "beef3": "BEEF3.SA",
    "vbbr3": "VBBR3.SA",
    "cvcb3": "CVCB3.SA",
    "cury3": "CURY3.SA",
    "dirr3": "DIRR3.SA",
    "jhsf3": "JHSF3.SA",
    "prio3": "PRIO3.SA",
    "ceab3": "CEAB3.SA",
    "itub3": "ITUB3.SA",
    "brav3": "BRAV3.SA",
    "bbse3": "BBSE3.SA",
    "gmat3": "GMAT3.SA",
    "brkm5": "BRKM5.SA",
    "ugpa3": "UGPA3.SA",
    "alpa4": "ALPA4.SA",
    "saud3": "SAUD3.SA",
    "mult3": "MULT3.SA",
    "pomo4": "POMO4.SA",
    "cyre3": "CYRE3.SA",
    "ecor3": "ECOR3.SA",
    "isae4": "ISAE4.SA",
    "tend3": "TEND3.SA",
    "klbn4": "KLBN4.SA",
    "pnvl3": "PNVL3.SA",
    "bbdc3": "BBDC3.SA",
    "embj3": "EMBJ3.SA",
    "sapr11": "SAPR11.SA",
    "lwsa3": "LWSA3.SA",
    "suzb3": "SUZB3.SA",
    "klbn11": "KLBN11.SA",
    "hapv3": "HAPV3.SA",
    "pcar3": "PCAR3.SA",
    "rcsl4": "RCSL4.SA",
    "azza3": "AZZA3.SA",
    "yduq3": "YDUQ3.SA",
    "slce3": "SLCE3.SA",
    "egie3": "EGIE3.SA",
    "smft3": "SMFT3.SA",
    "hbsa3": "HBSA3.SA",
    "vulc3": "VULC3.SA",
    "tims3": "TIMS3.SA",
    "auau3": "AUAU3.SA",
    "pgmn3": "PGMN3.SA",
    "csmg3": "CSMG3.SA",
    "flry3": "FLRY3.SA",
    "intb3": "INTB3.SA",
    "aure3": "AURE3.SA",
    "plpl3": "PLPL3.SA",
    "cbav3": "CBAV3.SA",
    "ggps3": "GGPS3.SA",
    "ljqq3": "LJQQ3.SA",
    "pmam3": "PMAM3.SA",
    "igti11": "IGTI11.SA",
    "hype3": "HYPE3.SA",
    "cash3": "CASH3.SA",
    "simh3": "SIMH3.SA",
    "ligt3": "LIGT3.SA",
    "caml3": "CAML3.SA",
    "seql3": "SEQL3.SA",
    "sbfg3": "SBFG3.SA",
    "viva3": "VIVA3.SA",
    "recv3": "RECV3.SA",
    "dxco3": "DXCO3.SA",
    "rapt4": "RAPT4.SA",
    "abcb4": "ABCB4.SA",
    "cpfe3": "CPFE3.SA",
    "bhia3": "BHIA3.SA",
    "sanb11": "SANB11.SA",
    "even3": "EVEN3.SA",
    "enju3": "ENJU3.SA",
    "espa3": "ESPA3.SA",
    "qual3": "QUAL3.SA",
    "logg3": "LOGG3.SA",
    "amer3": "AMER3.SA",
    "tfco4": "TFCO4.SA",
    "grnd3": "GRND3.SA",
    "brap4": "BRAP4.SA",
    "riaa3": "RIAA3.SA",
    "axia7": "AXIA7.SA",
    "klbn3": "KLBN3.SA",
    "engi11": "ENGI11.SA",
    "mypk3": "MYPK3.SA",
    "jall3": "JALL3.SA",
    "fesa4": "FESA4.SA",
    "alup11": "ALUP11.SA",
    "soja3": "SOJA3.SA",
    "hbor3": "HBOR3.SA",
    "mdia3": "MDIA3.SA",
    "kepl3": "KEPL3.SA",
    "cyre4": "CYRE4.SA",
    "posi3": "POSI3.SA",
    "mdne3": "MDNE3.SA",
    "tten3": "TTEN3.SA",
    "taee11": "TAEE11.SA",
    "smto3": "SMTO3.SA",
    "dasa3": "DASA3.SA",
    "pssa3": "PSSA3.SA",
    "jslg3": "JSLG3.SA",
    "mlas3": "MLAS3.SA",
    "azev4": "AZEV4.SA",
    "azte3": "AZTE3.SA",
    "fiqe3": "FIQE3.SA",
    "sapr4": "SAPR4.SA",
    "mils3": "MILS3.SA",
    "bmgb4": "BMGB4.SA",
    "unip6": "UNIP6.SA",
    "ambp3": "AMBP3.SA",
    "tupy3": "TUPY3.SA",
    "arml3": "ARML3.SA",
    "wizc3": "WIZC3.SA",
    "pine4": "PINE4.SA",
    "prnr3": "PRNR3.SA",
    "vveo3": "VVEO3.SA",
    "orvr3": "ORVR3.SA",
    "lavv3": "LAVV3.SA",
    "vtru3": "VTRU3.SA",
    "pass3": "PASS3.SA",
    "gfsa3": "GFSA3.SA",
    "rani3": "RANI3.SA",
    "seer3": "SEER3.SA",
    "mtre3": "MTRE3.SA",
    "bmob3": "BMOB3.SA",
    "brst3": "BRST3.SA",
    "vlid3": "VLID3.SA",
    "csed3": "CSED3.SA",
    "pomo3": "POMO3.SA",
    "shul4": "SHUL4.SA",
    "vitt3": "VITT3.SA",
    "irbr3": "IRBR3.SA",
    "desk3": "DESK3.SA",
    "oibr3": "OIBR3.SA",
    "usim3": "USIM3.SA",
    "blau3": "BLAU3.SA",
    "opct3": "OPCT3.SA",
    "azev3": "AZEV3.SA",
    "melk3": "MELK3.SA",
    "tasa4": "TASA4.SA",
    "hbre3": "HBRE3.SA",
    "eter3": "ETER3.SA",
    "aalr3": "AALR3.SA",
    "tris3": "TRIS3.SA",
    "alpk3": "ALPK3.SA",
    "brbi11": "BRBI11.SA",
    "rent4": "RENT4.SA",
    "syne3": "SYNE3.SA",
    "obtc3": "OBTC3.SA",
    "romi3": "ROMI3.SA",
    "fras3": "FRAS3.SA",
    "tgma3": "TGMA3.SA",
    "alld3": "ALLD3.SA",
    "jfen3": "JFEN3.SA",
    "toky3": "TOKY3.SA",
    "matd3": "MATD3.SA",
    "biom3": "BIOM3.SA",
    "leve3": "LEVE3.SA",
    "taee4": "TAEE4.SA",
    "ptbl3": "PTBL3.SA",
    "sapr3": "SAPR3.SA",
    "igti3": "IGTI3.SA",
    "vivr3": "VIVR3.SA",
    "ngrd3": "NGRD3.SA",
    "pfrm3": "PFRM3.SA",
    "meal3": "MEAL3.SA",
    "agro3": "AGRO3.SA",
    "amar3": "AMAR3.SA",
    "itsa3": "ITSA3.SA",
    "ifcm3": "IFCM3.SA",
    "dotz3": "DOTZ3.SA",
    "brkm3": "BRKM3.SA",
    "lpsb3": "LPSB3.SA",
    "taee3": "TAEE3.SA",
    "euca4": "EUCA4.SA",
    "pdtc3": "PDTC3.SA",
    "cmig3": "CMIG3.SA",
    "dexp3": "DEXP3.SA",
    "ggbr3": "GGBR3.SA",
    "rcsl3": "RCSL3.SA",
    "dmvf3": "DMVF3.SA",
    "csud3": "CSUD3.SA",
    "azul3": "AZUL3.SA",
    "sanb4": "SANB4.SA",
    "lupa3": "LUPA3.SA",
    "tpis3": "TPIS3.SA",
    "sanb3": "SANB3.SA",
    "aeri3": "AERI3.SA",
    "west3": "WEST3.SA",
    "haga4": "HAGA4.SA",
    "baza3": "BAZA3.SA",
    "bmeb4": "BMEB4.SA",
    "brap3": "BRAP3.SA",
    "tcsa3": "TCSA3.SA",
    "bsli3": "BSLI3.SA",
    "dexp4": "DEXP4.SA",
    "rnew4": "RNEW4.SA",
    "logn3": "LOGN3.SA",
    "inep3": "INEP3.SA",
    "goau3": "GOAU3.SA",
    "show3": "SHOW3.SA",
    "bpac3": "BPAC3.SA",
    "bsli4": "BSLI4.SA",
    "coce5": "COCE5.SA",
    "ucas3": "UCAS3.SA",
    "amob3": "AMOB3.SA",
    "land3": "LAND3.SA",
    "unip3": "UNIP3.SA",
    "inep4": "INEP4.SA",
    "tasa3": "TASA3.SA",
    "avll3": "AVLL3.SA",
    "bpac5": "BPAC5.SA",
    "mnpr3": "MNPR3.SA",
    "agxy3": "AGXY3.SA",
    "scar3": "SCAR3.SA",
    "rapt3": "RAPT3.SA",
    "wdcn3": "WDCN3.SA",
    "rnew3": "RNEW3.SA",
    "tecn3": "TECN3.SA",
    "pdgr3": "PDGR3.SA",
    "mgel4": "MGEL4.SA",
    "alup4": "ALUP4.SA",
    "alpa3": "ALPA3.SA",
    "snsy5": "SNSY5.SA",
    "ated3": "ATED3.SA",
    "hoot4": "HOOT4.SA",
    "cebr5": "CEBR5.SA",
    "engi3": "ENGI3.SA",
    "trad3": "TRAD3.SA",
    "eqpa3": "EQPA3.SA",
    "vste3": "VSTE3.SA",
    "ofsa3": "OFSA3.SA",
    "igti4": "IGTI4.SA",
    "dohl4": "DOHL4.SA",
    "cedo4": "CEDO4.SA",
    "psvm11": "PSVM11.SA",
    "epar3": "EPAR3.SA",
    "brsr3": "BRSR3.SA",
    "ealt3": "EALT3.SA",
    "camb3": "CAMB3.SA",
    "bees3": "BEES3.SA",
    "whrl4": "WHRL4.SA",
    "cebr6": "CEBR6.SA",
    "nutr3": "NUTR3.SA",
    "cgra4": "CGRA4.SA",
    "enmt3": "ENMT3.SA",
    "cedo3": "CEDO3.SA",
    "bees4": "BEES4.SA",
    "fict3": "FICT3.SA",
    "clsc4": "CLSC4.SA",
    "enmt4": "ENMT4.SA",
    "fher3": "FHER3.SA",
    "pine3": "PINE3.SA",
    "luxm4": "LUXM4.SA",
    "arnd3": "ARND3.SA",
    "cebr3": "CEBR3.SA",
    "engi4": "ENGI4.SA",
    "wlmm4": "WLMM4.SA",
    "bied3": "BIED3.SA",
    "whrl3": "WHRL3.SA",
    "alup3": "ALUP3.SA",
    "cgas5": "CGAS5.SA",
    "rpmg3": "RPMG3.SA",
    "rede3": "REDE3.SA",
    "azev11": "AZEV11.SA",
    "isae3": "ISAE3.SA",
    "telb4": "TELB4.SA",
    "oibr4": "OIBR4.SA",
    "ektr4": "EKTR4.SA",
    "bgip4": "BGIP4.SA",
    "rvee3": "RVEE3.SA",
    "mtsa4": "MTSA4.SA",
    "peab3": "PEAB3.SA",
    "bgip3": "BGIP3.SA",
    "ceeb3": "CEEB3.SA",
    "cgra3": "CGRA3.SA",
    "bmeb3": "BMEB3.SA",
    "peab4": "PEAB4.SA",
    "fesa3": "FESA3.SA",
    "telb3": "TELB3.SA",
    "haga3": "HAGA3.SA",
    "osxb3": "OSXB3.SA",
    "usim6": "USIM6.SA",
    "emae4": "EMAE4.SA",
    "bdll4": "BDLL4.SA",
    "rsul4": "RSUL4.SA",
    "aheb3": "AHEB3.SA",
    "jopa4": "JOPA4.SA",
    "rpad5": "RPAD5.SA",
    "bobr4": "BOBR4.SA",
    "bmks3": "BMKS3.SA",
    "pati3": "PATI3.SA",
    "crpg5": "CRPG5.SA",
    "ealt4": "EALT4.SA",
    "cbee3": "CBEE3.SA",
    "mndl3": "MNDL3.SA",
    "eqma3b": "EQMA3B.SA",
    "ctka4": "CTKA4.SA",
    "euca3": "EUCA3.SA",
    "balm4": "BALM4.SA",
    "estr4": "ESTR4.SA",
    "ctax3": "CTAX3.SA",
    "clsc3": "CLSC3.SA",
    "gepa4": "GEPA4.SA",
    "bmin4": "BMIN4.SA",
    "ppla11": "PPLA11.SA",
    "nord3": "NORD3.SA",
    "nexp3": "NEXP3.SA",
    "mspa3": "MSPA3.SA",
    "unip5": "UNIP5.SA",
    "plas3": "PLAS3.SA",
    "axia6": "AXIA6.SA",
    "dtcy3": "DTCY3.SA",
    "hbts5": "HBTS5.SA",
    "bdll3": "BDLL3.SA",
    "sond6": "SOND6.SA",
    "sond5": "SOND5.SA",
    "mrsa3b": "MRSA3B.SA",
    "wlmm3": "WLMM3.SA",
    "bnbr3": "BNBR3.SA",
    "snsy3": "SNSY3.SA",
    "bauh4": "BAUH4.SA",
    "cgas3": "CGAS3.SA",
    "balm3": "BALM3.SA",
    "pati4": "PATI4.SA",
    "crpg6": "CRPG6.SA",
    "mwet4": "MWET4.SA",
    "fiei3": "FIEI3.SA",
    "rpad6": "RPAD6.SA",
    "axia5": "AXIA5.SA",
    "gepa3": "GEPA3.SA",
    "cali3": "CALI3.SA",
    "bmin3": "BMIN3.SA",
    "aflt3": "AFLT3.SA",
    "cegr3": "CEGR3.SA",
    "frio3": "FRIO3.SA",
    "mapt4": "MAPT4.SA",
    "ceeb5": "CEEB5.SA",
}



def _normalize(text: str) -> str:
    text = unicodedata.normalize("NFD", text)
    text = "".join(c for c in text if unicodedata.category(c) != "Mn")
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def resolve_ticker(company_name: str) -> str | None:
    """Return the B3 ticker for a company name, or None if not in TICKER_MAP."""
    return TICKER_MAP.get(_normalize(company_name))


def fetch_market_data(ticker: str) -> dict:
    """
    Fetch snapshot + 2-year weekly history from Yahoo Finance.
    Synchronous — call via asyncio.to_thread(fetch_market_data, ticker) from async code.
    """
    t = yf.Ticker(ticker)
    info = t.info

    snapshot = {
        "price": info.get("currentPrice") if info.get("currentPrice") is not None else info.get("regularMarketPrice"),
        "market_cap": info.get("marketCap"),
        "pe_ratio": info.get("trailingPE"),
        "week_52_high": info.get("fiftyTwoWeekHigh"),
        "week_52_low": info.get("fiftyTwoWeekLow"),
        "currency": info.get("currency", "BRL"),

        # Valuation
        "forward_pe": info.get("forwardPE"),
        "price_to_book": info.get("priceToBook"),
        "price_to_sales": info.get("priceToSalesTrailing12Months"),
        "enterprise_value": info.get("enterpriseValue"),
        "ev_to_ebitda": info.get("enterpriseToEbitda"),
        "peg_ratio": info.get("trailingPegRatio") or info.get("pegRatio"),

        # Dividend
        "dividend_rate": info.get("dividendRate"),

        # Profitability / health
        "ebitda_margin": info.get("ebitdaMargins"),
        "roe": info.get("returnOnEquity"),
        "roa": info.get("returnOnAssets"),
        "profit_margin": info.get("profitMargins"),
        "operating_margin": info.get("operatingMargins"),
        "debt_to_equity": info.get("debtToEquity"),
        "current_ratio": info.get("currentRatio"),
        "total_cash": info.get("totalCash"),
        "total_debt": info.get("totalDebt"),
        "free_cashflow": info.get("freeCashflow"),
        "revenue_growth": info.get("revenueGrowth"),
        "earnings_growth": info.get("earningsGrowth"),

        # Analyst
        "recommendation": info.get("recommendationKey"),

        # Profile
        "employees": info.get("fullTimeEmployees"),
        "business_summary": info.get("longBusinessSummary"),
    }

    raw = t.history(period="5y", interval="1mo")
    if not raw.empty:
        monthly = raw["Close"].dropna()
        history = monthly.reset_index()
        history.columns = ["Date", "Close"]
    else:
        history = pd.DataFrame(columns=["Date", "Close"])

    return {"snapshot": snapshot, "history": history}


def format_market_sections(data: dict, company_name: str, ticker: str) -> list[dict]:
    """
    Split market data into labeled sections for citation.
    Returns list of {"section": name, "text": content}.
    Sections map to [1], [2], [3] in the LLM prompt.
    """
    snap = data["snapshot"]
    history: pd.DataFrame = data["history"]
    header = f"{company_name} ({ticker})"
    sections = []

    # --- Section 1: Cotação e Valuation ---
    s1 = [f"=== {header} — Cotação e Valuation ==="]
    if snap.get("price") is not None:
        s1.append(f"Preço atual: R$ {snap['price']:,.2f}")
    if snap.get("market_cap") is not None:
        s1.append(f"Market Cap: R$ {snap['market_cap'] / 1e9:,.1f} bi")
    if snap.get("pe_ratio") is not None:
        s1.append(f"P/L: {snap['pe_ratio']:.1f}")
    if snap.get("week_52_high") is not None:
        s1.append(f"Máxima 52 semanas: R$ {snap['week_52_high']:,.2f}")
    if snap.get("week_52_low") is not None:
        s1.append(f"Mínima 52 semanas: R$ {snap['week_52_low']:,.2f}")
    val_lines = []
    if snap.get("forward_pe") is not None:
        val_lines.append(f"P/L projetado: {snap['forward_pe']:.1f}")
    if snap.get("price_to_book") is not None:
        val_lines.append(f"P/VP: {snap['price_to_book']:.2f}")
    if snap.get("price_to_sales") is not None:
        val_lines.append(f"P/Receita: {snap['price_to_sales']:.2f}")
    if snap.get("enterprise_value") is not None:
        val_lines.append(f"Enterprise Value: R$ {snap['enterprise_value'] / 1e9:,.1f} bi")
    if snap.get("ev_to_ebitda") is not None:
        val_lines.append(f"EV/EBITDA: {snap['ev_to_ebitda']:.1f}")
    if snap.get("peg_ratio") is not None:
        val_lines.append(f"PEG: {snap['peg_ratio']:.2f}")
    if val_lines:
        s1.append("")
        s1.append("Valuation:")
        s1.extend(val_lines)
    if snap.get("dividend_rate") is not None:
        s1.append(f"Dividendo por ação (anual): R$ {snap['dividend_rate']:,.2f}")
    if snap.get("recommendation") is not None:
        s1.append(f"Recomendação dos analistas: {snap['recommendation']}")
    if len(s1) > 1:
        sections.append({"section": "Cotação e Valuation", "text": "\n".join(s1)})

    # --- Section 2: Rentabilidade e Saúde Financeira ---
    s2 = [f"=== {header} — Rentabilidade e Saúde Financeira ==="]
    if snap.get("ebitda_margin") is not None:
        s2.append(f"Margem EBITDA: {snap['ebitda_margin'] * 100:.1f}%")
    if snap.get("roe") is not None:
        s2.append(f"ROE: {snap['roe'] * 100:.1f}%")
    if snap.get("roa") is not None:
        s2.append(f"ROA: {snap['roa'] * 100:.1f}%")
    if snap.get("profit_margin") is not None:
        s2.append(f"Margem líquida: {snap['profit_margin'] * 100:.1f}%")
    if snap.get("operating_margin") is not None:
        s2.append(f"Margem operacional: {snap['operating_margin'] * 100:.1f}%")
    if snap.get("debt_to_equity") is not None:
        s2.append(f"Dívida/Patrimônio (D/E): {snap['debt_to_equity']:.1f}")
    if snap.get("current_ratio") is not None:
        s2.append(f"Liquidez corrente: {snap['current_ratio']:.2f}")
    if snap.get("total_cash") is not None:
        s2.append(f"Caixa total: R$ {snap['total_cash'] / 1e9:,.1f} bi")
    if snap.get("total_debt") is not None:
        s2.append(f"Dívida total: R$ {snap['total_debt'] / 1e9:,.1f} bi")
    if snap.get("free_cashflow") is not None:
        s2.append(f"Fluxo de caixa livre: R$ {snap['free_cashflow'] / 1e9:,.1f} bi")
    if snap.get("revenue_growth") is not None:
        s2.append(f"Crescimento da receita: {snap['revenue_growth'] * 100:.1f}%")
    if snap.get("earnings_growth") is not None:
        s2.append(f"Crescimento dos lucros: {snap['earnings_growth'] * 100:.1f}%")
    if snap.get("employees") is not None:
        s2.append(f"Funcionários: {snap['employees']:,}")
    if snap.get("business_summary") is not None:
        s2.append("")
        s2.append("Resumo da empresa:")
        s2.append(snap["business_summary"])
    if len(s2) > 1:
        sections.append({"section": "Rentabilidade e Saúde Financeira", "text": "\n".join(s2)})
        
# --- Section 3: Histórico de Preços ---
    if not history.empty:
        s3 = [f"=== {header} — Histórico de Preços (mensal, últimos 5 anos) ==="]
        s3.append("Data           Fechamento")
        for _, row in history.iterrows():
            date_str = str(row["Date"])[:10]
            s3.append(f"{date_str}   R$ {row['Close']:,.2f}")
        sections.append({"section": "Histórico de Preços", "text": "\n".join(s3)})

    if not sections:
        sections.append({
            "section": "Dados de Mercado",
            "text": f"Dados de mercado indisponíveis para {ticker}.",
        })

    return sections


def format_market_context(data: dict, company_name: str, ticker: str) -> str:
    """Format yfinance data as a single text block (joins all sections)."""
    return "\n\n".join(s["text"] for s in format_market_sections(data, company_name, ticker))